name: Continues Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: node common/scripts/install-run-rush.js install
      - run: node common/scripts/install-run-rush.js change -v

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: node common/scripts/install-run-rush.js publish -p -b master --include-all --set-access-level=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

