name: Publish NPM packages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: node common/scripts/install-run-rush.js install
      - run: node common/scripts/install-run-rush.js publish

